# =========================================
# DATASOURCE - SUPABASE PostgreSQL
# =========================================
spring.datasource.url=jdbc:postgresql://db.opcqwnlroimpacxgwlbi.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=123456789
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================================
# HIKARI CONNECTION POOL
# =========================================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

# =========================================
# JPA / HIBERNATE
# =========================================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate   # validar tablas existentes sin modificarlas

# =========================================
# LOGGING SQL (opcional)
# =========================================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
