# =========================================
# DATASOURCE - SUPABASE (FUNCIONA!)
# =========================================
spring.datasource.url=jdbc:postgresql://aws-1-ca-central-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.opcqwnlroimpacxgwlbi
spring.datasource.password=123456789

# =========================================
# JPA / HIBERNATE - CAMBIO CRÍTICO
# =========================================
spring.jpa.hibernate.ddl-auto=validate
# O usa:
# spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================================
# HIKARI CONNECTION POOL
# =========================================
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.allowPoolSuspension=true
spring.datasource.hikari.maximumPoolSize=10
spring.jpa.properties.hibernate.statement_cache.size=0

# =========================================
# SERVER
# =========================================
server.port=${PORT:8080}

# =========================================
# ACTUATOR
# =========================================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always